### ISSUE TITLE
[Question]: More content like this

### ISSUE THREAD

**Issue by hffmnn** [aws-samples/aws-serverless-airline-booking#135]
Hello,
thanks for this great project. I really like to learn by looking at complete projects like this one and not at tutorials that show just one aspect of an app or one service. Does anyone know if there is more content like this available somewhere? Does AWS provide more real world examples like this?

I'd be thankful for any hints!

**Comment by heitorlessa** [comment]
Hey @hffmnn,

Great to still hear this project is useful to anyone - I plan to make updates as described in the issues and board after reinvent.

As to your question, here are some that you'd surely find equally helpful - by complexity order

https://github.com/aws-samples/aws-serverless-ecommerce-platform

https://github.com/awslabs/realworld-serverless-application

https://github.com/aws-samples/aws-serverless-shopping-cart


The e-commerce is as complete example using EventBridge and custom tooling heavily focused on CI/CD and async patterns.

The Real world one is a sample inspired by how Serverless Application Repository (SAR) service was built

The Shopping Cart example is smaller but super easy to deploy, understand it, and find Perf areas to optimise it.

Hope that helps :)

Heitor Lessa

**Comment by hffmnn** [comment]
Hey @heitorlessa,

thanks a lot for that. Exactly what I was looking for, thank you.

Do you know if there are any plans at AWS to push more content like that? Content that shows, that it's a lot more than configuring a resource or using a service If not: Can you count this as a feature request? 😄

**Comment by heitorlessa** [comment]
Awesome to hear - Here’s one that *just literally came out*  from a friend
of mine

https://github.com/aws-samples/aws-bootstrap-kit-examples

As for feature requests, I’d suggest a few things:

1. Publicly voice that on Twitter with #awswishlist
2. Ask Developer Advocates (DA), e.g @munns, on Twitter and any social
media or public event about that
3. Ask your AWS representative e.g. Account Manager, Solutions
Architecture, or Technical Account Manager
4. For 1 and 2, mention the company you’re working with so we can count
that as a feature request ;-)

Due to the distributed nature at AWS, there isn’t a specific team per se.
These samples I shared are primarily driven by Solutions Architects, but
DAs are increasingly building more examples that you’re looking for.

As there are quite many, feel free to CC me (@heitor_lessa) on Twitter with
what you’re thinking is missing (or kudos), and I can bring that to some
folks attention ;-)

**Comment by hffmnn** [comment]
Big 👍 and thank you for that.
